lab/project/news/urls.py
from django.contrib import admin
from django.urls import re_path, path
from news import views
from .views import ArticleDetailView, ArticleView, HashtagView, RubrikaDetailView, RubrikaView

app_name = 'news'

urlpatterns = [
    path('', views.index, name="index"),
    
    path('rubric_detail/<int:rubric_id>/', RubrikaDetailView.rubric_detail, name='rubric_detail'),
    path('news_detail/<int:news_id>/', ArticleDetailView.news_detail, name='news_detail'),
    
    path('createRubrika/', RubrikaView.as_view(), name="createRubrika"),
    path('delete-rubrika/<int:rubrika_id>/', RubrikaView.delete_rubrika, name='delete_rubrika'),
    
    path('createHashtag/', HashtagView.as_view(), name="createHashtag"),
    path('delete-hashtag/<int:hashtag_id>/', HashtagView.delete_hashtag, name='delete_hashtag'),
    
    path('createArticle/', ArticleView.as_view(), name="createArticle"),
    path('delete-article/<int:article_id>/', ArticleView.delete_article, name='delete_article'),
    
    path('admin', admin.site.urls),
]

lab/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('news.urls')),
    path('admin/', admin.site.urls),
]

lab/project/news/models.py
from django.db import models

class Rubrika(models.Model):
    title = models.CharField (max_length = 120, blank=False)

    def __str__(self):
        return self.title
    
class Hashtag(models.Model):
    title = models.CharField(max_length = 120, blank=False)

    def __str__(self):
        return self.title
    
class Article(models.Model):
    rubNum_id = models.ForeignKey(Rubrika, on_delete=models.CASCADE)
    title = models.CharField(max_length = 120, blank=False)
    keywords = models.TextField(blank=False)
    annotation = models.TextField(blank=False)
    hashtags = models.ManyToManyField('Hashtag')

    def __str__(self):
        return self.title

lab/project/news/forms.py
from .models import Hashtag, Rubrika, Article
from django import forms
from django.forms import ModelForm

class HashtagForm(ModelForm):
    class Meta:
        model = Hashtag
        fields=['title']

class RubrikaForm(ModelForm):
    class Meta:
        model = Rubrika
        fields=['title']

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

lab/project/news/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View

from .forms import ArticleForm, HashtagForm, RubrikaForm
from .models import Article, Hashtag, Rubrika

def index(request):
    rubrics = Rubrika.objects.all()
    news_list = Article.objects.order_by('-id').all()
    return render(request, 'news/index.html', {'rubrics': rubrics, 'news_list': news_list})

class RubrikaDetailView:
    def rubric_detail(request, rubric_id):
        rubrics = Rubrika.objects.all()
        articles = Article.objects.filter(rubNum_id=rubric_id)
        return render(request, 'news/rubric_detail.html', {'rubrics': rubrics, 'articles': articles})

class ArticleDetailView(View):
    def news_detail(request, news_id):
        news = get_object_or_404(Article, pk=news_id)
        hashtags = news.hashtags.all()
        return render(request, 'news/news_detail.html', {'news': news, 'hashtags': hashtags})

class RubrikaView(View):
    def get(self, request):
        rubrics = Rubrika.objects.all()
        form = RubrikaForm()
        return render(request, 'news/createRubrika.html', {'rubrics': rubrics, 'form': form})

    def post(self, request):
        if request.method == "POST":
            form = RubrikaForm(request.POST)
            if form.is_valid():
                if not Rubrika.objects.filter(title=form.cleaned_data['title']).exists():
                    form.save()
                    return redirect('news:createRubrika')
                else:
                    return redirect('news:createRubrika')

        form = RubrikaForm()
        data = {'form': form}
        return render(request, "news/createRubrika.html", data)

    def delete_rubrika(request, rubrika_id):
        rubrika = Rubrika.objects.get(pk=rubrika_id)
        rubrika.delete()
        return redirect('news:createRubrika')
    
class HashtagView(View):
    def get(self, request):
        hashtags = Hashtag.objects.all()
        form = HashtagForm()
        return render(request, 'news/createHashtag.html', {'hashtags': hashtags, 'form': form})

    def post(self, request):
        if request.method == "POST":
            form = HashtagForm(request.POST)
            if form.is_valid():
                if not (Hashtag.objects.filter(title=form.cleaned_data['title']).exists()):
                    form.save()
                    return redirect('news:createHashtag')
                else:
                    return redirect('news:createHashtag')
        form = HashtagForm()
        data = {'form': form}
        return render(request, "news/createHashtag.html", data)

    def delete_hashtag(request, hashtag_id):
        hashtag = Hashtag.objects.get(pk=hashtag_id)
        hashtag.delete()
        return redirect('news:createHashtag')

class ArticleView(View):
    def get(self, request):
        articles = Article.objects.all()
        form = ArticleForm()
        return render(request, 'news/createArticle.html', {'articles': articles, 'form': form})

    def post(self, request):
        if request.method == "POST":
            form = ArticleForm(request.POST)
            if form.is_valid():
                if not(Article.objects.filter(title=form.cleaned_data['title']).exists()):
                    form.save()
                    return redirect('news:createArticle')
                else:
                    return redirect('news:createArticle')
        form = ArticleForm()
        data = {'form': form}
        return render(request, "news/createArticle.html", data)

    def delete_article(request, article_id):
        article = Article.objects.get(pk=article_id)
        article.delete()
        return redirect('news:createArticle')

lab/project/news/templates/news/createArticle.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Работа с новостями</title>
  <link rel="stylesheet" href="{% static 'stylesheets/foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheets/main.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheets/app.css' %}">
  <script src="{% static 'javascripts/modernizr.foundation.js' %}"></script>
  <link rel="stylesheet" href="{% static 'fonts/ligature.css' %}">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic' rel='stylesheet' type='text/css' />
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
</head>
<body>
<nav>
     <div class="twelve columns header_nav">
     <div class="row">
                 <ul id="menu-header" class="nav-bar horizontal">

        <li><a href="{% url 'news:index' %}">Главная</a></li>
        </ul>
      </div>
      </div>
</nav>
<form method="post" style="width:300px">
    {% csrf_token %}
        <p>Выберите рубрику</p>
        {{ form.rubNum_id }}
        <p>Напишите название</p>
        {{ form.title }}
        <p>Напишите описание</p>
        {{ form.keywords }}
        <p>Напишите содержимое новости</p>
        {{ form.annotation }}
        <p>Выберите хэштеги</p>
        {{ form.hashtags }}

    <button type="submit">Добавить новость</button>
</form>
<p>Список новостей</p>
  <ul>
    {% for article in articles %}
      <li>
        {{ article.title }}
        <a href="{% url 'news:delete_article' article.id %}">Удалить</a>
      </li>
    {% endfor %}
  </ul>

</body>
</html>

lab/project/news/templates/news/createHashtag.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Работа с хэштегами</title>
  <link rel="stylesheet" href="{% static 'stylesheets/foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheets/main.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheets/app.css' %}">
  <script src="{% static 'javascripts/modernizr.foundation.js' %}"></script>
  <link rel="stylesheet" href="{% static 'fonts/ligature.css' %}">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic' rel='stylesheet' type='text/css' />
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
</head>
<body>
<nav>
     <div class="twelve columns header_nav">
     <div class="row">
        <ul id="menu-header" class="nav-bar horizontal">
          <li><a href="{% url 'news:index' %}">Главная</a></li>
        </ul>
      </div>
      </div>
</nav>
<form method="post">
    <p>Название хэштега</p>
    {% csrf_token %}
    {{ form.title }}
    <button type="submit">Добавить хэштег</button>
</form>
  <ul>
    {% for hashtag in hashtags %}
      <li>
        {{ hashtag.title }}
            <a href="{% url 'news:delete_hashtag' hashtag.id %}">Удалить</a>
      </li>
    {% endfor %}
  </ul>
</body>
</html>

lab/project/news/templates/news/createRubrika.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Работа с рубриками</title>
  <link rel="stylesheet" href="{% static 'stylesheets/foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheets/main.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheets/app.css' %}">
  <script src="{% static 'javascripts/modernizr.foundation.js' %}"></script>
  <link rel="stylesheet" href="{% static 'fonts/ligature.css' %}">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic' rel='stylesheet' type='text/css' />
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
</head>
<body>
<nav>
     <div class="twelve columns header_nav">
     <div class="row">
        <ul id="menu-header" class="nav-bar horizontal">
          <li><a href="{% url 'news:index' %}">Главная</a></li>
        </ul>
      </div>
      </div>
</nav>
<form method="post">
    <p>Название рубрики</p>
    {% csrf_token %}
    {{ form.title }}
    <button type="submit">Добавить рубрику</button>
</form>
  <ul>
    {% for rubrika in rubrics %}
      <li>
          {{ rubrika.id }}
        {{ rubrika.title }}
        <a href="{% url 'news:delete_rubrika' rubrika.id %}">Удалить</a>
      </li>
    {% endfor %}
  </ul>
</body>
</html>

lab/project/news/templates/news/index.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>

  <meta charset="utf-8" />
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>Новости науки</title>
  
  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="{% static 'stylesheets/foundation.min.css' %}">
  <link rel="stylesheet" href="{% static 'stylesheets/main.css' %}">
  <link rel="stylesheet" href="{% static 'stylesheets/app.css' %}">

  <script src="javascripts/modernizr.foundation.js"></script>
  
  <link rel="stylesheet" href="{% static 'fonts/ligature.css' %}">
  
  <!-- Google fonts -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic' rel='stylesheet' type='text/css' />

  <!-- IE Fix for HTML5 Tags -->
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

</head>

<body>

<!-- ######################## Main Menu ######################## -->
 
<nav>
  <div class="twelve columns header_nav">
  <div class="row">
     <ul id="menu-header" class="nav-bar horizontal">
       <li><a href="{% url 'news:index' %}">Главная</a></li>
         {% for rubric in rubrics %}
           <li><a href="{% url 'news:rubric_detail' rubric.id %}">{{ rubric.title }}</a></li>
         {% endfor %}
     </ul>
   </div>  
   </div>
</nav><!-- END main menu -->
        
<!-- ######################## Header (featured posts) ######################## -->
     
<header>
   

        <div class="row">
        
        <h1>Новости науки</h1>
        
</header>
      
<!-- ######################## Section ######################## -->

<section>
  <div class="section_main">
      <div class="row">
          <section class="eight columns">
          {% for news in news_list %}
              <article class="blog_post">
                <div class="three columns">
                </div>
                <div class="nine columns">
                  <a href="{% url 'news:news_detail' news_id=news.id %}"><h4>{{ news.title }}</h4></a>
                  <p>{{ news.keywords }}</p>
                </div>
              </article>
        {% endfor %}
          </section>
      </div>
    </div>
</section>


<!-- ######################## Section ######################## -->

   <section>
   
      <div class="section_dark">
      <div class="row"> 
      
      <h2></h2>
      
          

      
      </div>
      </div>
      
    </section>


<!-- ######################## Footer ######################## -->  
      
<footer>

      <div class="row">
      
          <div class="twelve columns footer">
              <a href="" class="lsf-icon" style="font-size:16px; margin-right:15px" title="twitter">Twitter</a> 
              <a href="" class="lsf-icon" style="font-size:16px; margin-right:15px" title="facebook">Facebook</a>
              <a href="" class="lsf-icon" style="font-size:16px; margin-right:15px" title="pinterest">Pinterest</a>
              <a href="" class="lsf-icon" style="font-size:16px" title="instagram">Instagram</a>
          </div>
          
      </div>

</footer>		  

<!-- ######################## Scripts ######################## --> 

    <!-- Included JS Files (Compressed) -->
    <script src="{%static 'javascripts/foundation.min.js'%}" type="text/javascript"></script> 
    <!-- Initialize JS Plugins -->
     <script src="{% static 'javascripts/app.js' %}" type="text/javascript"></script>
</body>
</html>

lab/project/news/templates/news/news_detail.html
<!DOCTYPE html>
{% load static %}

<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>Новости науки</title>

  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="stylesheets/foundation.css">
  -->

  <link rel="stylesheet" href="{% static 'stylesheets/foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheets/main.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheets/app.css' %}">
  <script src="{% static 'javascripts/modernizr.foundation.js' %}"></script>
  <link rel="stylesheet" href="{% static 'fonts/ligature.css' %}">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic' rel='stylesheet' type='text/css' />
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>

</head>

<body>

<!-- ######################## Main Menu ######################## -->

<nav>
     <div class="twelve columns header_nav">
     <div class="row">
        <ul id="menu-header" class="nav-bar horizontal">
          <li><a href="{% url 'news:index' %}">Главная</a></li>
            {% for rubric in rubrics %}
              <li><a href="{% url 'news:rubric_detail' rubric.id %}">{{ rubric.title }}</a></li>
            {% endfor %}
        </ul>
      </div>
      </div>
</nav>

<!-- ######################## Header ######################## -->

    <header>

            <div class="row">
               <h1>        {{ news.title}}</h1>
    <article>

             <div class="twelve columns">
               <h2>    {{ news.keywords}}</h2></br>
                 {% for hashtag in hashtags %}
            <li>{{ hashtag.title }}</li>
        {% endfor %}
             </div>

    </article>


            </div>

    </header>

<!-- ######################## Section ######################## -->

<section class="section_light">


      <div class="row">


      <p>
        {{ news.annotation}}
      </p>

      </div>





<!-- ######################## Footer ######################## -->

<footer>

      <div class="row">

          <div class="twelve columns footer">
              <a href="" class="lsf-icon" style="font-size:16px; margin-right:15px" title="twitter">Twitter</a>
              <a href="" class="lsf-icon" style="font-size:16px; margin-right:15px" title="facebook">Facebook</a>
              <a href="" class="lsf-icon" style="font-size:16px; margin-right:15px" title="pinterest">Pinterest</a>
              <a href="" class="lsf-icon" style="font-size:16px" title="instagram">Instagram</a>
          </div>

      </div>

</footer>

<!-- ######################## Scripts ######################## -->

    <!-- Included JS Files (Compressed) -->
    <script src="javascripts/foundation.min.js" type="text/javascript"></script>
    <!-- Initialize JS Plugins -->
     <script src="javascripts/app.js" type="text/javascript"></script>
</body>
</html>

lab/project/news/templates/news/rubric_detail.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Новости науки</title>
  <link rel="stylesheet" href="{% static 'stylesheets/foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheets/main.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheets/app.css' %}">
  <script src="{% static 'javascripts/modernizr.foundation.js' %}"></script>
  <link rel="stylesheet" href="{% static 'fonts/ligature.css' %}">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic' rel='stylesheet' type='text/css' />
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
</head>
<body>

<!-- ######################## Main Menu ######################## -->
<nav>
     <div class="twelve columns header_nav">
     <div class="row">
        <ul id="menu-header" class="nav-bar horizontal">
          <li><a href="{% url 'news:index' %}">Главная</a></li>
            {% for rubric in rubrics %}
              <li><a href="{% url 'news:rubric_detail' rubric.id %}">{{ rubric.title }}</a></li>
            {% endfor %}
        </ul>
      </div>
      </div>
</nav>
<!-- END main menu -->
<!-- ######################## Header (featured posts) ######################## -->
<header>
        <div class="row">
        <h1>Новости науки</h1>
        </div>
</header>


<!-- ######################## Section ######################## -->
<section>
  <div class="section_main">
      <div class="row">
          <section class="eight columns">
              {% for article in articles %}
                  <article class="blog_post">
                     <div class="three columns">
                     </div>
                     <div class="nine columns">
                      <a href="{% url 'news:news_detail' news_id=article.id %}"><h4>{{ article.title }}</h4></a>
                      <p>{{ article.keywords }}</p>
                      </div>
                  </article>
              {% endfor %}
          </section>
          <section class="four columns">
            <H3>  &nbsp; </H3>
             <div class="panel">
              <h3>Админ-панель</h3>
                <ul class="accordion">
                  <li class="active">
                    <div class="title">
                       <a href="{% url 'news:createArticle' %}"><h5>Добавить статью</h5></a>
                    </div>
                  </li>
                    <li class="active">
                    <div class="title">
                       <a href="{% url 'news:createRubrika' %}"><h5>Добавить рубрику</h5></a>
                    </div>
                  </li>
                    <li class="active">
                    <div class="title">
                       <a href="{% url 'news:createHashtag' %}"><h5>Добавить хэштег</h5></a>
                    </div>
                  </li>
                </ul>
             </div>
</section>
      </div>
    </div>
</section>

<footer>
    <div class="row">
        <div class="twelve columns footer">
            <a href="" class="lsf-icon" style="font-size:16px; margin-right:15px" title="twitter">Twitter</a>
            <a href="" class="lsf-icon" style="font-size:16px; margin-right:15px" title="facebook">Facebook</a>
            <a href="" class="lsf-icon" style="font-size:16px; margin-right:15px" title="pinterest">Pinterest</a>
            <a href="" class="lsf-icon" style="font-size:16px" title="instagram">Instagram</a>
        </div>
    </div>
</footer>
<script src="{% static 'javascripts/foundation.min.js' %}" type="text/javascript"></script>
<script src="{% static  'javascripts/app.js' %}" type="text/javascript"></script>
</body>
</html>